// This file is automatically generated by the Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, use the "Change Firebase Project" command.
// Or, if you are using the VS Code extension, right-click on this file and
// select "Change Firebase Project".

// In your application code, you can use the following to get the Firebase
// project configuration:
//
// import { firebaseConfig } from "@/firebase/config";
//
// Your application will be automatically updated to use the new project
// when you change the active project.

/**
 * The Firebase project configuration.
 */
export const firebaseConfig = {
  "projectId": "trackverse-agji9",
  "appId": "1:183589332686:web:d1071b5f90c5c69fb6129f",
  "apiKey": "AIzaSyC6XPjMDzPv1BFYBPNhT7Bj6N6MR4ZVTXo",
  "authDomain": "trackverse-agji9.firebaseapp.com",
  "storageBucket": "trackverse-agji9.appspot.com",
  "messagingSenderId": "183589332686"
};
